Ext.define('GUMAS.model.User', {
    extend: 'Ext.data.Model',
    fields: [
        'id',
        'login',
        'password',
        'email',
        'role',
        'name',
        'surname',
        'location',
        'city',
        'joindate',
        'image',
        'team',
        'teamowner',
        'teambirth',
        'rating',
        'status',
        'sex',
        'birth',
        'aboutme',
        'skills',
        'msn',
        'yahoo',
        'skype',
        'icq',
        'mobile',
        'phone',
        'website',
        'contactemail'
    ]
});